
export const FoodList = [
    {"category": "Appetizers", "imgName": require("../../assets/spinachArtichoke.jpg"), "id": 1, "price": "10", "title": "Spinach Artichoke Dip", "description": "This spinach artichoke dip is delicious. It\'s so cheesy and fragrant. If you don\'t like artichokes, don\'t worry — you\'ll never know they\'re in there! My only question is: Is it okay to eat it with a spoon right out of the dish?" }, 
    {"category": "Appetizers", "imgName": require("../../assets/humus.jpg"), "id": 2, "price": "10", "title": "Hummus", "description": "Middle Eastern dip, spread, or savory dish made from cooked, mashed chickpeas blended with tahini, lemon juice, and garlic."}, 
    {"category": "Appetizers", "imgName": require("../../assets/friedCalamariRings.jpg"), "id": 3, "price": "5", "title": "Fried Calamari Rings", "description": "This fried calamari recipe is tender pieces of squid soaked in buttermilk, then coated in seasoned flour and deep fried to golden brown perfection. A quick and easy appetizer option that’s even better than what you’d get at a restaurant!"}, 
    {"category": "Appetizers", "imgName": require("../../assets/friedMushroom.jpg"), "id": 4, "price": "12", "title": "Fried Mushroom",  "description": "These fried mushrooms are coated in a light and crispy seasoned beer batter, then deep fried to golden brown perfection. The ultimate party snack that’s always a huge hit!"}, 
    {"category": "Salads", "imgName": require("../../assets/greekSalad.jpg"), "id": 5, "price": "7", "title": "Greek Salad", "description": "A traditional Greek salad consists of sliced cucumbers, tomatoes, green bell pepper, red onion, olives, and feta cheese. This classic combination is delicious, so I stick to it, just adding a handful of mint leaves for a fresh finishing touch."}, 
    {"category": "Salads", "imgName": require("../../assets/ceasarSalad.jpg"), "id": 6, "price": "7", "title": "Caesar", "description": "Caesar salad is made with romaine lettuce, croutons, Parmesan cheese, and Caesar dressing. The dressing is a mixture of olive oil, lemon juice, Worcestershire sauce, Dijon mustard, and garlic. Tip: Skip the shaky cheese. Shaved Parmesan makes a big difference with this dish, elevating both presentation and flavor."}, 
    {"category": "Salads", "imgName": require("../../assets/tunaSalad.jpg"), "id": 7, "price": "10", "title": "Tuna Salad", "description": "Tuna salad is a light and fresh comfort food classic. Made with a few simple ingredients such as canned tuna, mayonnaise, onion and celery, it’s the perfect combination of creamy and crispy. Serve this in a sandwich, wrap it in lettuce, or stuff it in avocado halves for a healthy, throw-together lunch."}, 
    {"category": "Salads", "imgName": require("../../assets/grilledChickenSalad.jpg"), "id": 8, "price": "12", "title": "Grilled Chicken Salad", "description": "This grilled chicken salad is tender marinated chicken that’s grilled to perfection then served over lettuce with bacon, avocado, corn, blue cheese and tomatoes. A hearty salad that’s packed with flavor and also happens to be full of nutrition."}, 
    {"category": "Beverages", "imgName": require("../../assets/waterB.jpg"), "id": 9, "price": "3", "title": "Water", "description": "Bottle of water!"}, 
    {"category": "Beverages", "imgName": require("../../assets/cokeB.jpg"), "id": 10, "price": "3", "title": "Coke", "description": "Bottle of Coke!"}, 
    {"category": "Beverages", "imgName": require("../../assets/beerB.jpg"), "id": 11, "price": "7", "title": "Beer", "description": "Bottle or fresh Beer!"}, 
    {"category": "Beverages", "imgName": require("../../assets/iceTeaB.jpg"), "id": 12, "price": "3", "title": "Iced Tea", "description": "Bottle of Ice Tea!"}
]